---
title: "analyse-R"
output:
  html_document:
    toc: false
---

```{r options, results='hide', echo=FALSE, message=FALSE, warning=FALSE}
if (Sys.info()["sysname"] == "Windows") {
  Sys.setlocale("LC_TIME", "french")
} else  {
  Sys.setlocale("LC_TIME", "fr_FR");
}
require(lubridate)
```


<div class="jumbotron">
  <h1>TP ANOVA <br />ISE 2  <br />2024-2025</h1>
  <p>Dernière mise à jour : `r I(today())`</p>
</div>


**Mr Youm**
**Moussa DIEME**




## Présentation{#presentation}

TP a rendre le 25

## Table des matières{#tdm}


```{r tdm semi-programmatique, message=FALSE, echo=FALSE}
base_url <- "http://larmarange.github.io/analyse-R/"
urls <- paste0(base_url, "index.html")

tdm <- function(section) {
  require(xml2)
  res <- "<div class=\"row\">\n"
  
  menu <- read_html("include/before_body.html", encoding = "UTF-8")
  section <- xml_find_first(menu, paste0(".//ul[@id='menu_", section, "']"))
  sous_sections <- xml_find_all(section, ".//ul")
  
  for (ss in sous_sections) {
    res <- paste0(res, "<div class=\"col-md-4\">\n")
    titre <- as.character(xml_contents(xml_find_first(ss, ".//li[@class='dropdown-header']")))
    Encoding(titre) <- "UTF-8"
    res <- paste0(res, "<p><strong>", titre, "</strong></p>\n")
    res <- paste0(res, "<div class=\"list-group\">\n")
    
    items <- xml_find_all(ss, ".//a")
    for (item in items) {
      lien <- xml_attr(item, "href")
      titre <- paste0(as.character(xml_contents(item)), collapse = "")
      Encoding(titre) <- "UTF-8"
      res <- paste0(res, "<a href=\"", lien,"\" class=\"list-group-item\">", titre, "</a>\n")
      urls <<- c(urls, paste0(base_url, lien))
    }

    res <- paste0(res, "</div>\n</div>\n\n")
  }
  
  res <- paste0(res, "</div>")
  return(res[1])
}
```

### Manipuler

```{r, results='asis', echo=FALSE, message=FALSE}
cat(tdm("manipuler"))
```